datasets: 'shapenetpart'
data_root: ''
num_classes: 16
num_parts:
  - 4
  - 2
  - 2
  - 4
  - 4
  - 3
  - 3
  - 2
  - 4
  - 2
  - 6
  - 2
  - 3
  - 3
  - 3
  - 3
input_features_dim:  3
batch_size:  16
num_points:  2048
num_workers:  4
# data augmentation
x_angle_range:  0.0
y_angle_range:  0.0
z_angle_range:  0.0
scale_low:  0.7
scale_high:  1.3
noise_std:  0.001
noise_clip:  0.05
translate_range:  0.0

# ---------------------------------------------------------------------------- #
# Model
# ---------------------------------------------------------------------------- #
backbone:  'resnet'
head:  'resnet_part_seg'
radius:  0.05
sampleDl:  0.02
nsamples:
  - 11
  - 25
  - 37
  - 36
  - 33
npoints:
  - 1280
  - 768
  - 192
  - 64
width:  144
depth:  2
bottleneck_ratio:  2

# ---------------------------------------------------------------------------- #
# Training options
# ---------------------------------------------------------------------------- #
epochs: 300
start_epoch:  1
base_learning_rate:  0.005
lr_scheduler:  'cosine'  # step,cosine
optimizer:  'adamW'
warmup_epoch:  -1
lr_decay_steps:  1
lr_decay_rate:  0.9885531
weight_decay:  0.00001
momentum:  0.9

# ---------------------------------------------------------------------------- #
# io and misc
# ---------------------------------------------------------------------------- #
load_path:  ''
print_freq:  10
save_freq:  10
val_freq:  10
log_dir:  './output'
local_rank:  0
amp_opt_level:  ''
rng_seed:  0

# ---------------------------------------------------------------------------- #
# Local Aggregation options
# ---------------------------------------------------------------------------- #
local_aggregation_type:  'pseudo_grid'
pseudo_grid:
  fixed_kernel_points: 'center'
  KP_influence: 'linear'
  KP_extent: 1.0
  num_kernel_points: 15
  convolution_mode: 'sum'
  output_conv: False
